/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecepcaoRouteImport } from './routes/recepcao'
import { Route as PacienteRouteImport } from './routes/paciente'
import { Route as MedicoRouteImport } from './routes/medico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestorRouteImport } from './routes/gestor'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecepcaoIndexRouteImport } from './routes/recepcao.index'
import { Route as PacienteIndexRouteImport } from './routes/paciente.index'
import { Route as MedicoIndexRouteImport } from './routes/medico.index'
import { Route as GestorIndexRouteImport } from './routes/gestor.index'
import { Route as RecepcaoPagamentosRouteImport } from './routes/recepcao.pagamentos'
import { Route as RecepcaoPacientesRouteImport } from './routes/recepcao.pacientes'
import { Route as RecepcaoCadastrarRouteImport } from './routes/recepcao.cadastrar'
import { Route as RecepcaoAgendaRouteImport } from './routes/recepcao.agenda'
import { Route as PacienteResultadosRouteImport } from './routes/paciente.resultados'
import { Route as PacienteAgendarRouteImport } from './routes/paciente.agendar'
import { Route as GestorUsuariosRouteImport } from './routes/gestor.usuarios'
import { Route as GestorMedicosRouteImport } from './routes/gestor.medicos'

const RecepcaoRoute = RecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteRoute = PacienteRouteImport.update({
  id: '/paciente',
  path: '/paciente',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicoRoute = MedicoRouteImport.update({
  id: '/medico',
  path: '/medico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorRoute = GestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcaoIndexRoute = RecepcaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecepcaoRoute,
} as any)
const PacienteIndexRoute = PacienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PacienteRoute,
} as any)
const MedicoIndexRoute = MedicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MedicoRoute,
} as any)
const GestorIndexRoute = GestorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestorRoute,
} as any)
const RecepcaoPagamentosRoute = RecepcaoPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => RecepcaoRoute,
} as any)
const RecepcaoPacientesRoute = RecepcaoPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => RecepcaoRoute,
} as any)
const RecepcaoCadastrarRoute = RecepcaoCadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => RecepcaoRoute,
} as any)
const RecepcaoAgendaRoute = RecepcaoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => RecepcaoRoute,
} as any)
const PacienteResultadosRoute = PacienteResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => PacienteRoute,
} as any)
const PacienteAgendarRoute = PacienteAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => PacienteRoute,
} as any)
const GestorUsuariosRoute = GestorUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => GestorRoute,
} as any)
const GestorMedicosRoute = GestorMedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => GestorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/gestor': typeof GestorRouteWithChildren
  '/login': typeof LoginRoute
  '/medico': typeof MedicoRouteWithChildren
  '/paciente': typeof PacienteRouteWithChildren
  '/recepcao': typeof RecepcaoRouteWithChildren
  '/gestor/medicos': typeof GestorMedicosRoute
  '/gestor/usuarios': typeof GestorUsuariosRoute
  '/paciente/agendar': typeof PacienteAgendarRoute
  '/paciente/resultados': typeof PacienteResultadosRoute
  '/recepcao/agenda': typeof RecepcaoAgendaRoute
  '/recepcao/cadastrar': typeof RecepcaoCadastrarRoute
  '/recepcao/pacientes': typeof RecepcaoPacientesRoute
  '/recepcao/pagamentos': typeof RecepcaoPagamentosRoute
  '/gestor/': typeof GestorIndexRoute
  '/medico/': typeof MedicoIndexRoute
  '/paciente/': typeof PacienteIndexRoute
  '/recepcao/': typeof RecepcaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/gestor/medicos': typeof GestorMedicosRoute
  '/gestor/usuarios': typeof GestorUsuariosRoute
  '/paciente/agendar': typeof PacienteAgendarRoute
  '/paciente/resultados': typeof PacienteResultadosRoute
  '/recepcao/agenda': typeof RecepcaoAgendaRoute
  '/recepcao/cadastrar': typeof RecepcaoCadastrarRoute
  '/recepcao/pacientes': typeof RecepcaoPacientesRoute
  '/recepcao/pagamentos': typeof RecepcaoPagamentosRoute
  '/gestor': typeof GestorIndexRoute
  '/medico': typeof MedicoIndexRoute
  '/paciente': typeof PacienteIndexRoute
  '/recepcao': typeof RecepcaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/gestor': typeof GestorRouteWithChildren
  '/login': typeof LoginRoute
  '/medico': typeof MedicoRouteWithChildren
  '/paciente': typeof PacienteRouteWithChildren
  '/recepcao': typeof RecepcaoRouteWithChildren
  '/gestor/medicos': typeof GestorMedicosRoute
  '/gestor/usuarios': typeof GestorUsuariosRoute
  '/paciente/agendar': typeof PacienteAgendarRoute
  '/paciente/resultados': typeof PacienteResultadosRoute
  '/recepcao/agenda': typeof RecepcaoAgendaRoute
  '/recepcao/cadastrar': typeof RecepcaoCadastrarRoute
  '/recepcao/pacientes': typeof RecepcaoPacientesRoute
  '/recepcao/pagamentos': typeof RecepcaoPagamentosRoute
  '/gestor/': typeof GestorIndexRoute
  '/medico/': typeof MedicoIndexRoute
  '/paciente/': typeof PacienteIndexRoute
  '/recepcao/': typeof RecepcaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/cadastro'
    | '/gestor'
    | '/login'
    | '/medico'
    | '/paciente'
    | '/recepcao'
    | '/gestor/medicos'
    | '/gestor/usuarios'
    | '/paciente/agendar'
    | '/paciente/resultados'
    | '/recepcao/agenda'
    | '/recepcao/cadastrar'
    | '/recepcao/pacientes'
    | '/recepcao/pagamentos'
    | '/gestor/'
    | '/medico/'
    | '/paciente/'
    | '/recepcao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/cadastro'
    | '/login'
    | '/gestor/medicos'
    | '/gestor/usuarios'
    | '/paciente/agendar'
    | '/paciente/resultados'
    | '/recepcao/agenda'
    | '/recepcao/cadastrar'
    | '/recepcao/pacientes'
    | '/recepcao/pagamentos'
    | '/gestor'
    | '/medico'
    | '/paciente'
    | '/recepcao'
  id:
    | '__root__'
    | '/'
    | '/alterar-senha'
    | '/cadastro'
    | '/gestor'
    | '/login'
    | '/medico'
    | '/paciente'
    | '/recepcao'
    | '/gestor/medicos'
    | '/gestor/usuarios'
    | '/paciente/agendar'
    | '/paciente/resultados'
    | '/recepcao/agenda'
    | '/recepcao/cadastrar'
    | '/recepcao/pacientes'
    | '/recepcao/pagamentos'
    | '/gestor/'
    | '/medico/'
    | '/paciente/'
    | '/recepcao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  CadastroRoute: typeof CadastroRoute
  GestorRoute: typeof GestorRouteWithChildren
  LoginRoute: typeof LoginRoute
  MedicoRoute: typeof MedicoRouteWithChildren
  PacienteRoute: typeof PacienteRouteWithChildren
  RecepcaoRoute: typeof RecepcaoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recepcao': {
      id: '/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof RecepcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente': {
      id: '/paciente'
      path: '/paciente'
      fullPath: '/paciente'
      preLoaderRoute: typeof PacienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medico': {
      id: '/medico'
      path: '/medico'
      fullPath: '/medico'
      preLoaderRoute: typeof MedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor': {
      id: '/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof GestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcao/': {
      id: '/recepcao/'
      path: '/'
      fullPath: '/recepcao/'
      preLoaderRoute: typeof RecepcaoIndexRouteImport
      parentRoute: typeof RecepcaoRoute
    }
    '/paciente/': {
      id: '/paciente/'
      path: '/'
      fullPath: '/paciente/'
      preLoaderRoute: typeof PacienteIndexRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/medico/': {
      id: '/medico/'
      path: '/'
      fullPath: '/medico/'
      preLoaderRoute: typeof MedicoIndexRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/gestor/': {
      id: '/gestor/'
      path: '/'
      fullPath: '/gestor/'
      preLoaderRoute: typeof GestorIndexRouteImport
      parentRoute: typeof GestorRoute
    }
    '/recepcao/pagamentos': {
      id: '/recepcao/pagamentos'
      path: '/pagamentos'
      fullPath: '/recepcao/pagamentos'
      preLoaderRoute: typeof RecepcaoPagamentosRouteImport
      parentRoute: typeof RecepcaoRoute
    }
    '/recepcao/pacientes': {
      id: '/recepcao/pacientes'
      path: '/pacientes'
      fullPath: '/recepcao/pacientes'
      preLoaderRoute: typeof RecepcaoPacientesRouteImport
      parentRoute: typeof RecepcaoRoute
    }
    '/recepcao/cadastrar': {
      id: '/recepcao/cadastrar'
      path: '/cadastrar'
      fullPath: '/recepcao/cadastrar'
      preLoaderRoute: typeof RecepcaoCadastrarRouteImport
      parentRoute: typeof RecepcaoRoute
    }
    '/recepcao/agenda': {
      id: '/recepcao/agenda'
      path: '/agenda'
      fullPath: '/recepcao/agenda'
      preLoaderRoute: typeof RecepcaoAgendaRouteImport
      parentRoute: typeof RecepcaoRoute
    }
    '/paciente/resultados': {
      id: '/paciente/resultados'
      path: '/resultados'
      fullPath: '/paciente/resultados'
      preLoaderRoute: typeof PacienteResultadosRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/paciente/agendar': {
      id: '/paciente/agendar'
      path: '/agendar'
      fullPath: '/paciente/agendar'
      preLoaderRoute: typeof PacienteAgendarRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/gestor/usuarios': {
      id: '/gestor/usuarios'
      path: '/usuarios'
      fullPath: '/gestor/usuarios'
      preLoaderRoute: typeof GestorUsuariosRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/medicos': {
      id: '/gestor/medicos'
      path: '/medicos'
      fullPath: '/gestor/medicos'
      preLoaderRoute: typeof GestorMedicosRouteImport
      parentRoute: typeof GestorRoute
    }
  }
}

interface GestorRouteChildren {
  GestorMedicosRoute: typeof GestorMedicosRoute
  GestorUsuariosRoute: typeof GestorUsuariosRoute
  GestorIndexRoute: typeof GestorIndexRoute
}

const GestorRouteChildren: GestorRouteChildren = {
  GestorMedicosRoute: GestorMedicosRoute,
  GestorUsuariosRoute: GestorUsuariosRoute,
  GestorIndexRoute: GestorIndexRoute,
}

const GestorRouteWithChildren =
  GestorRoute._addFileChildren(GestorRouteChildren)

interface MedicoRouteChildren {
  MedicoIndexRoute: typeof MedicoIndexRoute
}

const MedicoRouteChildren: MedicoRouteChildren = {
  MedicoIndexRoute: MedicoIndexRoute,
}

const MedicoRouteWithChildren =
  MedicoRoute._addFileChildren(MedicoRouteChildren)

interface PacienteRouteChildren {
  PacienteAgendarRoute: typeof PacienteAgendarRoute
  PacienteResultadosRoute: typeof PacienteResultadosRoute
  PacienteIndexRoute: typeof PacienteIndexRoute
}

const PacienteRouteChildren: PacienteRouteChildren = {
  PacienteAgendarRoute: PacienteAgendarRoute,
  PacienteResultadosRoute: PacienteResultadosRoute,
  PacienteIndexRoute: PacienteIndexRoute,
}

const PacienteRouteWithChildren = PacienteRoute._addFileChildren(
  PacienteRouteChildren,
)

interface RecepcaoRouteChildren {
  RecepcaoAgendaRoute: typeof RecepcaoAgendaRoute
  RecepcaoCadastrarRoute: typeof RecepcaoCadastrarRoute
  RecepcaoPacientesRoute: typeof RecepcaoPacientesRoute
  RecepcaoPagamentosRoute: typeof RecepcaoPagamentosRoute
  RecepcaoIndexRoute: typeof RecepcaoIndexRoute
}

const RecepcaoRouteChildren: RecepcaoRouteChildren = {
  RecepcaoAgendaRoute: RecepcaoAgendaRoute,
  RecepcaoCadastrarRoute: RecepcaoCadastrarRoute,
  RecepcaoPacientesRoute: RecepcaoPacientesRoute,
  RecepcaoPagamentosRoute: RecepcaoPagamentosRoute,
  RecepcaoIndexRoute: RecepcaoIndexRoute,
}

const RecepcaoRouteWithChildren = RecepcaoRoute._addFileChildren(
  RecepcaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  CadastroRoute: CadastroRoute,
  GestorRoute: GestorRouteWithChildren,
  LoginRoute: LoginRoute,
  MedicoRoute: MedicoRouteWithChildren,
  PacienteRoute: PacienteRouteWithChildren,
  RecepcaoRoute: RecepcaoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
